CODE_PATH = "/home/ron/Govt-API/PythonBase/" #path for code base
ORIGINAL_FILE = "/home/ron/Govt-API/data" #where original data is kept
PROP_DB_PATH = "/home/ron/Govt-API/sqlite/proposal.s3" #path for database
SOLR_DB_PATH = "/home/ptr/workgroup/database/solrdata.s3" #path for solr database backup information
LOC_DB_PATH = "/home/ptr/workgroup/database/locdata.s3" #path for newly relocated file data
SOLR_URL = "http://localhost:"
SOLR_UPDATE_URL = "solr/update"
SOLR_BINARY_UPLOAD = "--data-binary"
SOLR_FILE_CONTENT = "-H 'Content-type:application/xml"
OPATH = "/home/ptr/docfiles"
YSTART = 1997 #start of proposal date range
YEND = 2012 #end of proposal date range
SOLRPRIPORT = 9000 #internal port for solr public instance
SOLRPUBPORT = 9001 #internal port for solr private instance
FSEARCH_PATH_LIST = "/home/dnewman/update/"
FSEARCH_LOCAL = "/home/ptr/data/2012-05-15/"
