CODE_PATH = "/home/ron/Govt-API/PythonBase/" #path for code base
ORIGINAL_FILE = "/home/ron/Govt-API/data" #where original data is kept
PROP_DB_PATH = "/home/ron/Govt-API/sqlite/proposal.s3" #path for database
SOLR_DB_PATH = "/home/ptr/workgroup/database/solrdata.s3" #path for solr database backup information
LOC_DB_PATH = "/home/ptr/workgroup/database/locdata.s3" #path for newly relocated file data
SOLR_URL = "http://localhost:"
SOLR_UPDATE_URL = "solr/update"
SOLR_BINARY_UPLOAD = "--data-binary"
SOLR_FILE_CONTENT = "-H 'Content-type:application/xml"
OPATH = "/home/ptr/docfiles"
YSTART = 1997 #start of proposal date range
YEND = 2012 #end of proposal date range
SOLRPRIPORT = 9000 #internal port for solr public instance
SOLRPUBPORT = 9001 #internal port for solr private instance
FSEARCH_PATH_LIST = "/home/dnewman/update/"
FSEARCH_LOCAL = "/home/ptr/data/2012-05-15/"
PDF_ARCHIVE = "/home/ptr/data/pdf_archive/"
NWF_ARCHIVE = "/home/ptr/data/nwf_archive/"
XML_ARCHIVE = "/home/ptr/data/xml_archive/"
#SQL result defines
NSF_ID = 0
DD_DATE = 1
status = 2
#File extension search results
DOC_FOUND = 0
PDF_FOUND = 1 
PDF_LOC = 2
XML_FOUND = 3
XML_LOC = 4
NWF_FOUND = 5
NWF_LOC = 6
